### ISSUE TITLE
How welcome are pull requests that introduce non standard Icons?

### ISSUE THREAD

**Issue by LokiMidgard** [Gudradain/spirit-island-template#12]
I currently playing around with some icons not present in the current version of the game.

E.g. I needed an icon for `forget power card` and this is what I thought of

![image](https://user-images.githubusercontent.com/389101/101404354-d0131380-38d6-11eb-96e8-db9c7e7a1d43.png)

If interested I could add it to your template and make a pull request.

**Comment by LordMotas** [comment]
If no one else sees a problem with it, I think something like that would be really cool. Eventually the goal is to be able to allow any kind of custom Spirit be created. I would definitely be open to it.
