### ISSUE TITLE
Minor Display issue with / for land targeting on power cards

### ISSUE THREAD

**Issue by TheRealFlyingPotato** [Gudradain/spirit-island-template#30]
When trying to use different land possibilities for targeting, it has an unexpected result. Preferred:

![image](https://user-images.githubusercontent.com/19823667/110218847-84461b00-7e81-11eb-9ffa-ec491b4b25ae.png)

Result:
![image](https://user-images.githubusercontent.com/19823667/110218835-6d9fc400-7e81-11eb-8098-392dafbd9cd3.png)
Also results bad if trying to use land types.
![image](https://user-images.githubusercontent.com/19823667/110218878-bb1c3100-7e81-11eb-97e7-b2e5d863cebd.png)
![image](https://user-images.githubusercontent.com/19823667/110218889-c8d1b680-7e81-11eb-952a-bf1d8831e2f4.png)

I'll try to dig for a possible solution if I can.

**Comment by resonant-gamedesign** [comment]
I think the solution would be to change the width from 70px to 45px of info-target icon in "card.css"

info-target icon{
  width:45px;
  height:32px;
}

I found 45px to be a nice sweet spot. It's possible it would be too small with some icons, but perhaps those could get a specific class. A more robust solution would scale when using the / but that would be a lot more work I think.
