### ISSUE TITLE
Letter spacing in Innate Powers

### ISSUE THREAD

**Issue by resonant-gamedesign** [Gudradain/spirit-island-template#33]
In the Innate-Power.css file, I think that "  letter-spacing: -0.5px;" should be added to 'level'.

Is there a better way for me to provide this feedback? I'm new to Github, have a casual amount of coding experience.

**Comment by LordMotas** [comment]
This way is fine to provide such feedback. We can use that feedback to improve the templates in future updates.

**Comment by resonant-gamedesign** [comment]
Would I be able to contribute to the code? I've already made a few changes to my local copy.
I've worked on the elements in growth section. I've modified the multiple element text to allow for X Y or Z, and I've also implemented have 2 of one element.
I've updated some of the image files to use the more recent ones from the wiki. I've tweaked the spacing on Special Rules so some icons appear more in line with the text.
I've modified the spirit image so it fills the panel automatically - and the spirit-image-scale now works as well.

**Comment by LordMotas** [comment]
If you've already cloned the repo, you should be able to push up a new branch and create a pull request to merge in. If not, we may need to get you permissions to join as a collaborator.

**Comment by resonant-gamedesign** [comment]
I've got it branched. This is my first time using GitHub, though I'm familiar with the idea. I'll sort out how to use it and then hopefully do some pulls.
I assume the work gets reviewed - I'm a decent coder but pretty new to CSS and using javascript this way, so I might break convention.

**Comment by resonant-gamedesign** [comment]
Sorry, I have it FORKED, not branched. Not sure how to start a branch.

**Comment by LokiMidgard** [comment]
> Sorry, I have it FORKED, not branched. Not sure how to start a branch.

That is exactly what you needed :)

You can make a branch on your fork or not, that dosen't matter for this repo.

When you push changes in your repo you should see on the website a button `create pull requst` otherwise you can open the menu `Contribute` to create a pull request:
![image](https://user-images.githubusercontent.com/389101/151392652-13277b22-1c50-4901-865e-11cd535665bd.png)

![image](https://user-images.githubusercontent.com/389101/151392819-06cc8e3b-4ce8-4b34-8b13-828ce5b7e386.png)

**Comment by resonant-gamedesign** [comment]
Is development active? I'm pretty excited to contribute but was wondering if it would be a productive use of my time. I'm definitely not expecting responses right away or anything, but I'd like to know if the project is basically shelved at the moment.

**Comment by LokiMidgard** [comment]
I think it is, but from my experience issues and pull requests will not handled immediately.

Are you on the Discard server? There is a dedicated [channel for templates](https://discord.com/channels/707232612355276913/730094854671040574)
