### ISSUE TITLE
Growth text for gaining elements is slightly unaligned

### ISSUE THREAD

**Issue by resonant-gamedesign** [Gudradain/spirit-island-template#34]
I've been fiddling around a bit, so it might just be on my end, but the text for gaining an element during growth appears to be a few pixels lower than other items (such as gaining energy or reclaiming).
Changing the margin-bottom on "growth-cell icon." series of classes to 7 appears to nearly solve the issue. I suspect there is a more uniform solution out there, but not sure.

**Comment by resonant-gamedesign** [comment]
(This is solved in my Pull request)

**Comment by LokiMidgard** [comment]
@resonant-gamedesign by the way, you can write `fixes #34` in a commit and I think also in the text of the pull request. if Merged it will automaticly close the corresponding issue. And you know exactly wich pull request it was (assuming you may want to make more then one 😉)
